services:
  postgres:
    image: postgres:18
    container_name: wb-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wb_feedbacks
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - wb-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: wb-backend
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wb-network

volumes:
  pgdata:

networks:
  wb-network:
    driver: bridge